### ISSUE TITLE
new users might be getting registered in BP with their MLA API IDs

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-auth#12]
So many acronyms. 

Not totally sure if this is a bug or not, but this doesn't look right. Just leaving this here so I don't forget about this. 

![selection_517](https://cloud.githubusercontent.com/assets/1843676/6718927/b54fa0a0-cd8d-11e4-945e-58c422b833a8.png)

**Comment by chriszarate** [comment]
Good catch, seems like it should be their WP id. If we need their MLA id in this context (not sure we do), I believe we were using `mla_oid`.

**Comment by JonathanReeve** [comment]
Luckily, this was only a problem with test functions, and not with cbox-auth functions. Fixed in 9f882086f03091161a52b5f71901f3f30055d5ed or thereabouts.
