### ISSUE TITLE
after login, redirect user to previously accessed page

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-auth#13]
If a user tries to visit, say, http://commons.mla.org/?some-query-to-accept-an-invitation-or-something, a logged-out user will be redirected to the login page. After logging in, that user should be redirected to the page he/she was trying to visit in the first place, rather than redirected to the home page.

**Comment by JonathanReeve** [comment]
This issue was migrated from mlaa/cbox-mla#102.

**Comment by JonathanReeve** [comment]
This one is super tricky. I can redirect users to their referring URL, so that if they click "login" from, say, /activity, they can be redirected back to /activity after login (this is done by setting a cookie the value of `$_COOKIE['HTTP_REFERER']`), but some places, like `members/<username>/messages/`, which automatically redirect to the login screen, inexplicably don't get passed referring URLs in `$_SERVER`, making it impossible to redirect users to `/members/<username>/messages` with this method. I'll ask around and see if anyone else has any ideas.

**Comment by kfitz** [comment]
Was just reminded of this bug by attempting to follow a link to a doc when I wasn't logged in. No further insight; just a reminder that it's still an issue.

**Comment by chriszarate** [comment]
Fixed in 76758838aedb1bcda66ce30a71eecf16106f0e1d.
