### ISSUE TITLE
Echoed "You have successfully joined the group" message

### ISSUE THREAD

**Issue by chriszarate** [mlaa/cbox-auth#14]
To reproduce (tested on Sinclair):

1. Visit /groups/ and join a group from that page.
2. Visit a different group's page.
3. You will receive a message that you have successfully joined the group, even though it you didn't.

The technical term for this is "delayed reaction."

![joined-group](https://cloud.githubusercontent.com/assets/739304/6790337/4ed3f382-d17d-11e4-9170-ae1fa2e7d02a.png)

**Comment by JonathanReeve** [comment]
I think this is actually the normal behavior on production, too. I'll test it on vanilla CBOX next, and if it exists there, as well, I'll file a report upstream.

**Comment by JonathanReeve** [comment]
Yep, it's on vanilla CBOX, too. I'll file a report with BuddyPress.

**Comment by JonathanReeve** [comment]
[Bug report filed upstream](https://buddypress.trac.wordpress.org/ticket/6364).

**Comment by chriszarate** [comment]
Fixed.
