### ISSUE TITLE
group page body breaks on joining large groups

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-auth#15]
Moved from mlaa/cbox-mla#248. 

This is a very odd and mysterious bug. From what I can tell so far, it happens: 
 * only on old VMs (a new VM doesn't seem to have this bug)
 * only on large groups
 * only when joining the group
 * only when cbox-auth is newer than f47b53a.

**Comment by JonathanReeve** [comment]
![selection_523](https://cloud.githubusercontent.com/assets/1843676/6847365/77055b54-d39c-11e4-964c-e236085364ea.png)

**Comment by chriszarate** [comment]
If you can't replicate on new VM (newer codebase, fresher DB import), then ... WONTFIX?

**Comment by JonathanReeve** [comment]
My thoughts exactly. So at the moment this only affects Sinclair.
