### ISSUE TITLE
Unshared Academic Interest Brings Up Odd Message

### ISSUE THREAD

**Issue by terrainsvagues** [mlaa/cbox-auth#20]
If I click on ["panoramic literature"](https://thoreau.mlacommons.org/members/?s=panoramic+literature), I get a message saying "viewing 1 active member" (me, I presume, as nobody else shares this interest) but I am not actually viewing any active members. 
![screen shot 2015-04-20 at 9 34 08 am](https://cloud.githubusercontent.com/assets/7083891/7230992/559b6c8a-e740-11e4-9f5e-3c1757ea4824.png)

**Comment by chriszarate** [comment]
Fixed.
