### ISSUE TITLE
logging in using Commons pw leads to Error 434 message 

### ISSUE THREAD

**Issue by kshkim** [mlaa/cbox-auth#21]
Using my mla.org password works fine, but I can't log in using my Commons password. Leads to this message: 

![mla commons log in clipular](https://cloud.githubusercontent.com/assets/8835589/7231170/c7621624-e741-11e4-97e3-521f66c6db8e.png)

**Comment by JonathanReeve** [comment]
Thanks for reporting this, Katherine! Looks like it speaks to something awry on the DB/DocStudio side. As Chris is taking care of that end of it, I'll close this issue here.
