### ISSUE TITLE
option to change email status for a group when visiting it for the first time as a member

### ISSUE THREAD

**Issue by terrainsvagues** [mlaa/cbox-auth#22]
This might exist on the production site too, but it would be good to offer a "Change this" link to the email preferences page (after "Your group email status is..." the first time a member visits a group after joining. 
![screen shot 2015-04-20 at 9 42 14 am](https://cloud.githubusercontent.com/assets/7083891/7231194/f47b91a8-e741-11e4-9377-d36e6a1fe468.png)

**Comment by JonathanReeve** [comment]
Good idea. I'll slate this for 2.3.1.

**Comment by chriszarate** [comment]
Wishlist.
