### ISSUE TITLE
automatically expand abbreviations in titles and institutional affiliations? 

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-auth#23]
This would expand abbreviations like "Eng" -> "English," "Prof" -> "Professor," and so on. 

Potential problems: 
 * a single abbreviation might be used for more than one word. This might be the sort of thing that is obvious to humans based on context, but a dictionary expansion might not be able to handle.
 * omitted words will still be missing, such that "Prof Eng" will expand to "Professor English" instead of "Professor of English."

**Comment by JonathanReeve** [comment]
We might be able to solve the second potential problem by expanding all instances of "Prof" to "Professor of," and all instances of "Dir" to "Director of."

**Comment by chriszarate** [comment]
Wishlist.
