### ISSUE TITLE
Allow limited nonmember access

### ISSUE THREAD

**Issue by chriszarate** [mlaa/cbox-auth#24]
Details will be filed separately.

**Comment by JonathanReeve** [comment]
Nonmembers are now allowed in (7f5236a33ced9be5728c88693d17f6c4b0345c30), so long as they have the usermeta key `mla_nonmember` and value `yes`. This flag is set whenever a super-admin adds a new user network-wide, in `wp-admin/network/users.php` (see mlaa/cbox-mla@6e7d239c349df5f4370b199f41879a2af3133eb4). However, adding new users in this way is not fully tested. The user may also have to be added to the child Commons site (`wp-admin/users.php`), and may need to activate an account and set a password using untested mechanisms. I'll close this issue and add a separate issue for testing that.
