### ISSUE TITLE
Member being dropped from committee

### ISSUE THREAD

**Issue by chriszarate** [mlaa/cbox-auth#28]
It appears that a member is being dropped from a committee (M026) on API sync.

**Comment by terrainsvagues** [comment]
Oh! And I have found the other member who was getting dropped before (and has, I just realized, been dropped again): Luís Madureira (Commons user name: 65814)

**Comment by chriszarate** [comment]
Found issue: members do not have `mla_commons_mem` flag set in member record.

**Comment by chriszarate** [comment]
Ok, this is all fixed up on the API side.
