### ISSUE TITLE
add message indicating that credentials are the same as for mla.org

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-auth#3]

**Comment by JonathanReeve** [comment]
How about this? Other suggestions for copy?

![selection_472](https://cloud.githubusercontent.com/assets/1843676/5727998/09c4298e-9b35-11e4-8a1c-2c350978a6e3.png)

**Comment by terrainsvagues** [comment]
I would just say "use your mla.org credentials to log in." And perhaps bold it. And then "Forgot your log in information?" since any mention of user name may confuse members who only think in terms of membership number.

**Comment by JonathanReeve** [comment]
Cool. How about this: 

![selection_473](https://cloud.githubusercontent.com/assets/1843676/5728134/064bcc8e-9b36-11e4-960b-2d1636c1db69.png)

(I'm guessing it's 1. "log in" and 2. "login.")

**Comment by terrainsvagues** [comment]
That looks right to me. And it fits on one line, which is always nice.

**Comment by JonathanReeve** [comment]
Reopening per meeting. Change "mla.org" to "MLA," change "login" to "log-in," and run by editorial.

**Comment by JonathanReeve** [comment]
Opened internal issue 4250 for copyediting this.

**Comment by JonathanReeve** [comment]
Copy from Editorial is: 

    User name: 
    Password: 
    Use your MLA credentials to log in.
    Forgotten your log-in credentials?

**Comment by JonathanReeve** [comment]
![selection_495](https://cloud.githubusercontent.com/assets/1843676/6025828/75922494-aba3-11e4-980f-e3c773394a3a.png)
