### ISSUE TITLE
Group/member sync disparity

### ISSUE THREAD

**Issue by chriszarate** [mlaa/cbox-auth#32]
We've further narrowed down an API sync issue and determined that the group sync removes a member and the member sync adds the member back.

Details in Slack.

**Comment by modelm** [comment]
MLAAPI call organizations/149?joined_commons=*N* shows the missing members.

organizations/149?joined_commons=*Y* does not show the missing members, and that's what the groups page is using so when it loads it thinks they're not members and removes them.

**Comment by modelm** [comment]
Fixed for future username validation/creation by https://github.com/mlaa/commons/commit/cdec045af4e145b07086f26ddba82b0d9ee8d6e9
